### PR TITLE
perf: quince release support

### PR DESCRIPTION
**Pull request by luisfelipec95**
## Description

This PR adds support for the Open edx Quince release.

## Testing instructions

1. Create an environment with Quince release, you can use [Tutor](https://docs.tutor.overhang.io/index.html) or [TVM](https://github.com/eduNEXT/tvm)
2. Install the Django private plugin eox-audit-model using this PR branch, you can use steps in [Tutor documentation](https://docs.tutor.overhang.io/configuration.html#installing-extra-xblocks-and-requirements).
3. Configure [eox-core](https://github.com/eduNEXT/eox-core) as is shown in the [eox-core test cases document](https://docs.google.com/document/d/1gaQyHBGDDkvy_NsFw07MRV6uI2R49CeWCDHzTVi_TiI/edit#heading=h.2tnvhqtb6so6)
4. Run the [test cases](https://docs.google.com/document/d/1v6mxFSf1k7JrxU36Ok9uVDFBhtxVuGmhFLtxtbIsPFs/edit); **in this same file you can find more information about the plugin configurations** 

## Aditional information
[JIRA ISSUE DS-787](https://edunext.atlassian.net/jira/software/c/projects/DS/boards/40?selectedIssue=DS-787)

### CODE REVIEW

**Comment by bra-i-am** [comment]
hello @luisfelipec95, I hope you're doing great c:

I've just tested the main functionality and everything is working as expected. Nonetheless, it is happening again the thing with the labeler workflow where is not failing but the Label is not being applied; remember to use `codelytv/pr-size-labeler@v1.7.0`

**Comment by bra-i-am** [comment]
hello @luisfelipec95, I hope you're doing great c:

I've just tested the main functionality and everything is working as expected. Nonetheless, first, please change the name of the PR :v

... and second, it is happening the thing with the labeler workflow where is not failing but the Label is not being applied; remember to use `codelytv/pr-size-labeler@v1.7.0`

PD: That was a mistake of Brayan from the past, sorry jaja

**Comment by bra-i-am** [comment]
hello @luisfelipec95, I hope you're doing great c:

I've just tested the main functionality and everything is working as expected. Nonetheless, it is happening the thing with the labeler workflow where is not failing but the Label is not being applied; remember to use `codelytv/pr-size-labeler@v1.7.0`

PD: That was a mistake of Brayan from the past, sorry jaja

**Review by bra-i-am — APPROVED** [review]
LGTM!

**Review by Alec4r — APPROVED** [review]

**Pull request merged**
