### PR TITLE
perf: sumac release support

### PR DESCRIPTION
**Pull request by luisfelipec95**
## Description

This PR aims to support the new Sumac Release

## Testing instructions

1, Create a Sumac environment using Tutor or TVM.
2. Install eox-audit-model using this branch you can follow the official [tutor documentation](https://docs.tutor.overhang.io/configuration.html#installing-extra-xblocks-and-requirements).
3. Follow the [test cases ](https://docs.google.com/document/d/1_3_GaugvK5HqPOGUII0HYnWhoDPDzsFPpbo1LyXdu1g/edit?tab=t.0#heading=h.lrqwgvik5cjh)file.

## Additional information

https://github.com/eduNEXT/eox-release/issues/183

### CODE REVIEW

**Comment by magajh** [comment]
@luisfelipec95 As part of the process for supporting the new release, please review (and merge if necessary) the PRs opened by Dependabot: https://github.com/eduNEXT/eox-audit-model/pull/42
We need to keep the workflow dependencies as up-to-date as possible

**Comment by magajh** [comment]
@luisfelipec95 I think we can mark this PR as ready for review and leave the update it here once you've run all test cases in the remote environment

**Comment by luisfelipec95** [comment]
The test cases were executed locally, pending in stage

**Comment by luisfelipec95** [comment]
The test cases have already been tested in the remote sumac environment

**Review by magajh — APPROVED** [review]
LGTM

**Comment by magajh** [comment]
@luisfelipec95 is this branch updated with the latest changes in master?

**Review by Asespinel — APPROVED** [review]
I did some testing in my local and everything is working

**Pull request merged**
