### PR TITLE
feat: add absolute uri to djrf-api audit decorator

### PR DESCRIPTION
**Pull request by johanseto**
## Description

Hi, I am adding some audits to my views for the plugin Nelp. So I am using djrf decorator thats is nice saving the data of the request. 

image

But  I would like to add the  URL like eox-tagging do it with path. 
image

The djrf decorator only uses the data in the args but not kwargs.
I think that the url is useful to filter or now some extra data of the input.

## BEFORE
Only args are used.

## AFTER

Peek 2023-06-02 16-28

## Testing instructions

Clone this branch, add the decorator to a djrf method in a view, and then test the audit fields.

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [x] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Comment by santiagosuarezedunext** [comment]
Since it is a PR I am going to move it directly to prioritized and we will analyze it in subsequent sprints

**Comment by JuanDavidBuitrago** [comment]
Hi @johanv26, sorry for the delay.
We are trying to solve some tasks with a higher priority, and we will start reviewing this soon.

**Comment by JuanDavidBuitrago** [comment]
For now, the team can't review this PR. We have some priorities, but we expect to solve this as soon as possible.
Sorry for the delay, and thanks for your patience.

**Comment by Asespinel** [comment]
@santiagosuarezedunext Do we have any plans to review this PR in a future sprint?

**Comment by MaferMazu** [comment]
@johanseto, do you still want to merge this?

**Comment by johanseto** [comment]
> @johanseto, do you still want to merge this?

Yes, I think that could be useful for djrf views using the decorator.

**Review by MaferMazu — APPROVED** [review]
It works as expected. Thanks for this, @johanseto.

**Pull request merged**
